# Generated by Django 5.1.5 on 2025-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog_user',
            table='blog_users',
        ),
        migrations.AlterModelTable(
            name='blogs',
            table='blog_posts',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='blog_categories',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='blog_comments',
        ),
        migrations.AlterModelTable(
            name='followers',
            table='blog_followers',
        ),
        migrations.AlterModelTable(
            name='post_like',
            table='blog_post_likes',
        ),
    ]
