# Generated by Django 5.1.5 on 2025-04-23 05:59

#import Blog.components.GoogleStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_blog_user_table_alter_blogs_table_and_more'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='blog_user',
    #         name='profile_img',
    #         field=models.FileField(null=True, storage=Blog.components.GoogleStorage.GoogleDriveStorage, upload_to=''),
    #     ),
    #     migrations.AlterField(
    #         model_name='blogs',
    #         name='blog_img',
    #         field=models.FileField(null=True, storage=Blog.components.GoogleStorage.GoogleDriveStorage, upload_to=''),
    #     ),
    #     migrations.AlterField(
    #         model_name='categories',
    #         name='image',
    #         field=models.FileField(null=True, storage=Blog.components.GoogleStorage.GoogleDriveStorage, upload_to=''),
    #     ),
    # ]
