# Generated by Django 5.1.5 on 2025-04-23 12:59

#import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_blog_user_profile_img_alter_blogs_blog_img_and_more'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='blog_user',
    #         name='profile_img',
    #         field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile'),
    #     ),
    #     migrations.AlterField(
    #         model_name='blogs',
    #         name='blog_img',
    #         field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blogs'),
    #     ),
    #     migrations.AlterField(
    #         model_name='categories',
    #         name='image',
    #         field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='categories'),
    #     ),
    # ]
